### ISSUE TITLE
Font not working

### ISSUE THREAD

**Issue by VolticFroogo** [OliverHinde/HTML-and-CSS-Course#1]
[Here](https://github.com/OliverHinde/HTML-and-CSS-Course/blob/716e87609795c9f242d14251c5a2c3de0769991e/2.%20CSS%20Basics/12_form_styling.html#L8) it says:

```CSS
<linkhref="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"/>
```

However I believe it should be:

```CSS
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"/>
```

The font doesn't work right now as the tag is link with href as a parameter not linkhref.

**Comment by OliverHinde** [comment]
Fixed in [this commit](https://github.com/OliverHinde/HTML-and-CSS-Course/commit/1e51e178f6e4a60dd2195fd9cd20fddfb8b26b7f)
